name: Update state

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Scheduled trigger (12AM / 12PM every day)
  schedule:
    - cron: '0 12,0 * * *'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: "main"
          submodules: recursive
          persist-credentials: false
      - name: Fetch state
        run: |
          git fetch origin state
          git worktree add ./state state
      - name: Updating state
        run: |
          ./update.py state
          pushd state
          git config user.name 'Stern SPIKE Database (update workflow)'
          git config user.email '<>'
          git commit -a -m "Update state"
          echo "COMMIT_STATUS=$?" >> $GITHUB_ENV
          popd
      - name: Pushing state
        if: env.COMMIT_STATUS == '0'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pushd state
          git push "https://${PAT_TOKEN}@github.com/${{ github.repository }}.git"
          curl -X POST \
            -H "Authorization: token ${PAT_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "state-updated"}'
          popd