name: Update state

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Scheduled trigger (12AM / 12PM every day)
  schedule:
    - cron: '0 12,0 * * *'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: "main"
          submodules: recursive
          persist-credentials: false
      - name: Fetch state
        run: |
          git fetch origin state
          git worktree add ./state state
      - name: Updating state
        run: |
          ./update.py state
          pushd state
          git config user.name 'Stern SPIKE Database (update workflow)'
          git config user.email '<>'
          git commit -a -m "Update state"
          popd
      - name: Pushing state
        env:
          PAT_OWNER: ${{ secrets.PAT_OWNER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pushd state
          git push "https://${PAT_OWNER}:${PAT_TOKEN}@github.com/${{ github.repository }}.git"
          popd