name: Update state

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Scheduled trigger (12AM / 12PM every day)
  schedule:
    - cron: '0 12,0 * * *'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: "main"
          submodules: recursive
      - name: Fetch state
        run: |
          git fetch origin state
          git worktree add ./state state
      - name: Updating state
        run: |
          ./update.py state
          pushd state
          git config user.name 'Stern SPIKE Database (update workflow)'
          git config user.email '<>'
          git commit -a -m "Update state"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}